### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by Whon1980-DL** [Whon1980-DL/love-running#3]
In order to **store previous poll data** as an **administrator**, I can **store information on Excel and have automate system to enter data**.

#### Acceptance Criteria:
* Acceptance Criteria 1: Have an application that is linked to a Google sheet
* Acceptance Criteria 2: Being able to automate spreadsheet data update
* Acceptance Criteria 3: Have clear instruction on how to enter data to ensure its validity
---
### Task
- [ ] Create Google Sheet and grant access and edit to linked application
- [ ] Code HTML and CSS to make UI of the terminal appealing
- [ ] Code using Python to allow data input from terminal
- [ ]  Code to ensure all data input are valid and appropriate for future use and analysis
